version: 2.1

jobs:
  build-and-package:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Build Application
          command: make
      - run:
          name: Package
          command: zip -r ./BtBatStat.zip ./dist/BtBatStat.app
      - store_artifacts:
          path: ./BtBatStat.zip
workflows:
  sample:
    jobs:
      - build-and-package